### ISSUE TITLE
Sync local eXist-DB applications with GitHub code

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#1]
I know it's possible to do this with [webhooks](https://gist.github.com/wsalesky/bf26507ff593f0c99a35) but I've never used them before.

**Comment by wsalesky** [comment]
@aso2101 Have you tried installing the crypto module on the newest version of eXist?

**Comment by aso2101** [comment]
I have, and it seems to work. I'd like to give webhooks another try.

**Comment by wsalesky** [comment]
Great. Do we have a script? Or do I need to give you one? Also, are you able to add environment variables to your server? If so we can store the git-sync code in the app, which is the best long term solution.

**Comment by aso2101** [comment]
I don't have a script. But I should be able to add environment variables to the server.

By the way, I now see that Wolfgang Meier wrote a program for getting data from a GitHub repository into an eXist-DB library: https://github.com/sarit/sarit-data

**Comment by wsalesky** [comment]
Interesting. I had not seen that. So the scripts do slightly different things, but either could work for your data. Wolfgang's script is triggered by the user (a button on the data app page triggers the script to pull the data from github), my script uses github webhooks to sync to the data repository and respond to any 'push' event to the master branch. 

I do not think Wolfgang's script requires any (github) authorization, so that could simplify the update process. Let me know which approach you prefer and I will set something up.

**Comment by aso2101** [comment]
I think we should put this issue on ice for now. So far there haven't been any real problems in updating the data manually. And I suspect that synchronization with GitHub/GitLab etc. is something that eXist will probably add in future versions.
